# Generated by Django 5.2.3 on 2026-06-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_logs', '0005_call_sim'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=50)),
                ('received_by', models.CharField(max_length=100)),
                ('sim', models.CharField(blank=True, default='', max_length=100)),
                ('direction', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='incoming', max_length=10)),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('missed', 'Missed'), ('rejected', 'Rejected')], max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alabama_calllog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AlabamaCallLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=50)),
                ('call_status', models.CharField(max_length=20)),
                ('duration', models.IntegerField(default=0)),
                ('call_time', models.DateTimeField()),
                ('received_by', models.CharField(blank=True, max_length=100)),
                ('sim', models.CharField(blank=True, default='', max_length=100)),
                ('query', models.TextField(blank=True)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/')),
                ('quotation_filename', models.CharField(blank=True, max_length=255)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('follow_up_note', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('return_called', models.BooleanField(default=False)),
                ('return_called_at', models.DateTimeField(blank=True, null=True)),
                ('lead_status', models.CharField(choices=[('active', 'Active'), ('junk', 'Junk'), ('irrelevant', 'Irrelevant')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='call_logs.alabamacalllog')),
            ],
            options={
                'db_table': 'alabama_calllead',
                'ordering': ['-call_time'],
            },
        ),
    ]
