# Generated by Django 5.2.3 on 2026-06-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='business_phone_id',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='whatsappoutbound',
            name='business_phone_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
