# Generated by Django 5.2.3 on 2026-06-19 12:08

from django.db import migrations, models


def mark_existing_read(apps, schema_editor):
    """Treat all messages that exist before this feature as already seen, so the
    new unread badge doesn't light up every historical conversation on deploy."""
    WhatsAppLead = apps.get_model('leads', 'WhatsAppLead')
    WhatsAppLead.objects.update(read=True)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_broadcastjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapplead',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_read, migrations.RunPython.noop),
    ]
