# Generated by Django 5.2.3 on 2026-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_whatsapplead_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlabamaBroadcastJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('phone_id', models.CharField(blank=True, max_length=40)),
                ('total', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='running', max_length=10)),
                ('errors', models.TextField(blank=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alabama_broadcastjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlabamaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mobile_no', models.CharField(blank=True, max_length=30)),
                ('email_id', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('items', models.TextField(blank=True)),
                ('sales_person', models.CharField(blank=True, max_length=100)),
                ('quotation', models.CharField(blank=True, max_length=100)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/')),
                ('quotation_date', models.DateField(blank=True, null=True)),
                ('follow_up1_date', models.DateField(blank=True, null=True)),
                ('follow_up1_notes', models.TextField(blank=True)),
                ('follow_up2_date', models.DateField(blank=True, null=True)),
                ('follow_up2_notes', models.TextField(blank=True)),
                ('lead_status', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'alabama_lead',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlabamaWhatsAppLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('business_phone_id', models.CharField(blank=True, max_length=40)),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('text_body', models.TextField(blank=True)),
                ('msg_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio')], default='text', max_length=20)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='whatsapp_inbound/')),
                ('media_name', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('reply_text', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'alabama_whatsapplead',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='AlabamaWhatsAppOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=30)),
                ('business_phone_id', models.CharField(blank=True, max_length=40)),
                ('msg_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio')], default='text', max_length=20)),
                ('text_body', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='whatsapp_outbound/')),
                ('media_name', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alabama_whatsappoutbound',
                'ordering': ['sent_at'],
            },
        ),
    ]
