# Generated by Django 5.2.3 on 2026-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_whatsapplead_business_phone_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('phone_id', models.CharField(blank=True, max_length=40)),
                ('total', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='running', max_length=10)),
                ('errors', models.TextField(blank=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
